version: '3'
services:
  backend:
    build:
      context: server/
    ports:
      - "8080:8080"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_API_URL: http://${FTGO_BACKEND_HOST:-localhost}:8080
    ports:
      - "5000:5000"
